// modules/storage.js
// Datos del curso — estructura: Curso > Fases > Temas

export const courseData = {
  id: 'fullstack-dev',
  title: 'Full Stack Dev',
  subtitle: 'De cero a profesional',
  phases: [
    {
      id: 'phase-fundamentos',
      title: 'FUNDAMENTOS',
      emoji: '🧱',
      topics: [
        {
          id: 'terminal',
          title: 'Terminal',
          emoji: '💻',
          description: 'Domina la línea de comandos desde cero. Navega, gestiona archivos y automatiza tareas.',
          completed: true,
          mainVideo: {
            youtubeId: 'nZ1DMMsyVUI',
            title: 'Terminal completo — Curso intensivo',
            duration: '4h 20m',
          },
          highlights: [
            { time: '0:00',   label: 'Introducción a la terminal' },
            { time: '12:30',  label: 'Navegación con cd, ls, pwd' },
            { time: '35:10',  label: 'Gestión de archivos y carpetas' },
            { time: '1:10:00',label: 'Permisos y propietarios' },
            { time: '1:50:20',label: 'Variables de entorno' },
            { time: '2:30:00',label: 'Scripting Bash básico' },
            { time: '3:15:45',label: 'Pipes y redirecciones' },
            { time: '3:58:00',label: 'Comandos avanzados y aliases' },
          ],
          chapters: [
            {
              id: 'ch-terminal-1',
              title: 'Primeros pasos',
              description: 'Introducción y navegación básica',
              youtubeId: 'nZ1DMMsyVUI',
              startAt: 0,
              highlights: [
                { time: '0:00',  label: 'Presentación' },
                { time: '12:30', label: 'cd, ls, pwd' },
              ],
            },
            {
              id: 'ch-terminal-2',
              title: 'Gestión de ficheros',
              description: 'mkdir, rm, cp, mv y permisos',
              youtubeId: 'nZ1DMMsyVUI',
              startAt: 2110,
              highlights: [
                { time: '35:10', label: 'Crear y borrar' },
                { time: '1:10:00',label: 'chmod y chown' },
              ],
            },
            {
              id: 'ch-terminal-3',
              title: 'Scripting & Automatización',
              description: 'Bash scripts, pipes y aliases',
              youtubeId: 'nZ1DMMsyVUI',
              startAt: 9000,
              highlights: [
                { time: '2:30:00', label: 'Variables y condicionales' },
                { time: '3:15:45', label: 'Pipes y redirecciones' },
              ],
            },
          ],
        },
        {
          id: 'git',
          title: 'Git',
          emoji: '🌿',
          description: 'Control de versiones profesional. Ramas, merge, rebase y flujos de trabajo en equipo.',
          completed: true,
          mainVideo: {
            youtubeId: 'ANF1X42_ae4',
            title: 'Git y GitHub — De cero a experto',
            duration: '5h 10m',
          },
          highlights: [
            { time: '0:00',   label: 'Qué es Git y por qué usarlo' },
            { time: '20:00',  label: 'init, add, commit' },
            { time: '55:30',  label: 'Ramas y merge' },
            { time: '1:40:00',label: 'GitHub y remote' },
            { time: '2:30:00',label: 'Rebase y cherry-pick' },
            { time: '3:10:00',label: 'Hooks y automatización' },
          ],
          chapters: null,
        },
      ],
    },
    {
      id: 'phase-web',
      title: 'WEB BASE',
      emoji: '🌐',
      topics: [
        {
          id: 'html',
          title: 'HTML',
          emoji: '🏗️',
          description: 'Estructura semántica, accesibilidad y las bases del documento web.',
          completed: false,
          mainVideo: {
            youtubeId: 'kUMe1FH4CHE',
            title: 'HTML desde cero — Curso completo',
            duration: '4h 48m',
          },
          highlights: [
            { time: '0:00',   label: 'Estructura básica del documento' },
            { time: '30:00',  label: 'Etiquetas semánticas' },
            { time: '1:00:00',label: 'Formularios y validación' },
            { time: '1:45:00',label: 'Media: img, video, audio' },
            { time: '2:20:00',label: 'Accesibilidad y ARIA' },
            { time: '3:00:00',label: 'SEO básico' },
          ],
          chapters: null,
        },
        {
          id: 'css',
          title: 'CSS',
          emoji: '🎨',
          description: 'Estilos, layout avanzado, Flexbox, Grid, animaciones y diseño responsivo.',
          completed: false,
          mainVideo: {
            youtubeId: 'wZniZEbPAzk',
            title: 'CSS completo — De básico a avanzado',
            duration: '5h 30m',
          },
          highlights: [
            { time: '0:00',   label: 'Selectores y especificidad' },
            { time: '45:00',  label: 'Box model y display' },
            { time: '1:30:00',label: 'Flexbox completo' },
            { time: '2:30:00',label: 'CSS Grid' },
            { time: '3:20:00',label: 'Animaciones y transiciones' },
            { time: '4:10:00',label: 'Variables CSS y custom properties' },
            { time: '4:50:00',label: 'Media queries y responsive' },
          ],
          chapters: [
            {
              id: 'ch-css-1',
              title: 'Fundamentos CSS',
              description: 'Selectores, box model y herencia',
              youtubeId: 'wZniZEbPAzk',
              startAt: 0,
              highlights: [
                { time: '0:00',  label: 'Intro y selectores' },
                { time: '45:00', label: 'Box model' },
              ],
            },
            {
              id: 'ch-css-2',
              title: 'Layout Moderno',
              description: 'Flexbox y Grid en profundidad',
              youtubeId: 'wZniZEbPAzk',
              startAt: 5400,
              highlights: [
                { time: '1:30:00', label: 'Flexbox' },
                { time: '2:30:00', label: 'Grid' },
              ],
            },
            {
              id: 'ch-css-3',
              title: 'CSS Avanzado',
              description: 'Animaciones, variables y responsive',
              youtubeId: 'wZniZEbPAzk',
              startAt: 12000,
              highlights: [
                { time: '3:20:00', label: 'Animaciones' },
                { time: '4:50:00', label: 'Responsive' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'phase-js',
      title: 'JAVASCRIPT',
      emoji: '⚡',
      topics: [
        {
          id: 'javascript',
          title: 'JavaScript',
          emoji: '⚡',
          description: 'El lenguaje de la web. Variables, funciones, DOM, asincronía, y el ecosistema JS moderno.',
          completed: false,
          mainVideo: {
            youtubeId: 'Ber2pi2C0j8',
            title: 'JavaScript — Curso completo desde cero',
            duration: '6h 12m',
          },
          highlights: [
            { time: '0:00',   label: 'Tipos de datos y variables' },
            { time: '50:00',  label: 'Funciones y scope' },
            { time: '1:40:00',label: 'Arrays y objetos' },
            { time: '2:30:00',label: 'DOM y eventos' },
            { time: '3:20:00',label: 'Promesas y async/await' },
            { time: '4:10:00',label: 'ES6+: desestructuración, spread' },
            { time: '5:00:00',label: 'Módulos y import/export' },
            { time: '5:45:00',label: 'Fetch API y peticiones HTTP' },
          ],
          chapters: [
            {
              id: 'ch-js-1',
              title: 'Bases de JS',
              description: 'Tipos, variables, condicionales y bucles',
              youtubeId: 'Ber2pi2C0j8',
              startAt: 0,
              highlights: [
                { time: '0:00', label: 'Tipos de datos' },
                { time: '50:00', label: 'Funciones' },
              ],
            },
            {
              id: 'ch-js-2',
              title: 'DOM y Eventos',
              description: 'Manipulación del DOM y eventos del navegador',
              youtubeId: 'Ber2pi2C0j8',
              startAt: 9000,
              highlights: [
                { time: '2:30:00', label: 'Selección de elementos' },
                { time: '3:00:00', label: 'Event listeners' },
              ],
            },
            {
              id: 'ch-js-3',
              title: 'Asincronía',
              description: 'Callbacks, Promesas y async/await',
              youtubeId: 'Ber2pi2C0j8',
              startAt: 12000,
              highlights: [
                { time: '3:20:00', label: 'Promesas' },
                { time: '4:00:00', label: 'async/await' },
                { time: '5:45:00', label: 'Fetch API' },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'phase-backend',
      title: 'BACKEND',
      emoji: '⚙️',
      topics: [
        {
          id: 'nodejs',
          title: 'Node.js',
          emoji: '🟢',
          description: 'JavaScript en el servidor. Express, REST APIs, middleware y autenticación.',
          completed: false,
          mainVideo: {
            youtubeId: 'yB4n_K7dZV8',
            title: 'Node.js y Express — Curso completo',
            duration: '4h 55m',
          },
          highlights: [
            { time: '0:00',   label: 'Qué es Node.js y npm' },
            { time: '35:00',  label: 'Módulos y require/import' },
            { time: '1:10:00',label: 'Express — rutas básicas' },
            { time: '2:00:00',label: 'Middleware y cors' },
            { time: '2:50:00',label: 'JWT y autenticación' },
            { time: '3:45:00',label: 'Conexión a base de datos' },
          ],
          chapters: null,
        },
        {
          id: 'databases',
          title: 'Bases de Datos',
          emoji: '🗄️',
          description: 'SQL y NoSQL. PostgreSQL, MongoDB, modelado de datos y consultas avanzadas.',
          completed: false,
          mainVideo: {
            youtubeId: 'OqjGjpjDEoU',
            title: 'SQL completo con PostgreSQL',
            duration: '5h 20m',
          },
          highlights: [
            { time: '0:00',   label: 'Bases relacionales vs NoSQL' },
            { time: '30:00',  label: 'CRUD básico' },
            { time: '1:15:00',label: 'Joins y relaciones' },
            { time: '2:10:00',label: 'Índices y optimización' },
            { time: '3:00:00',label: 'Transacciones' },
          ],
          chapters: null,
        },
      ],
    },
  ],
};